services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saveit
    command: sh -c "pnpm prisma generate && pnpm prisma migrate deploy && pnpm start"
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./.env:/app/.env

